/* DHost UX enhancements: pinned bots, true bot grid, and reliable long-press reorder. */
(() => {
  const ORDER_KEY = 'dhost.botOrder.v2';
  const PIN_KEY = 'dhost.botPinned.v2';
  const COL_KEY = 'dhost.botColumns.v2';
  const read = (key, fallback) => { try { const v = JSON.parse(localStorage.getItem(key)); return v ?? fallback; } catch (_) { return fallback; } };
  const write = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); } catch (_) {} };

  let order = Array.isArray(read(ORDER_KEY, null)) ? read(ORDER_KEY, []) : (Array.isArray(read('dhost.botOrder.v1', [])) ? read('dhost.botOrder.v1', []) : []);
  let pinned = Array.isArray(read(PIN_KEY, null)) ? read(PIN_KEY, []) : (Array.isArray(read('dhost.botPinned.v1', [])) ? read('dhost.botPinned.v1', []) : []);
  let columns = Math.max(1, Math.min(4, Number(read(COL_KEY, read('dhost.botColumns.v1', 1))) || 1));
  let drag = null;
  let longPressTimer = null;
  let suppressClickUntil = 0;

  const PIN = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m14 4 6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/><path d="M12 12 5 5l4-4 7 7"/><path d="m4 20 3-3"/></svg>';
  const PIN_OFF = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m4 4 16 16"/><path d="M14 4l6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/></svg>';

  const STYLE = `
    .home-screen .bot-list{display:grid!important;grid-template-columns:repeat(var(--bot-columns,1),minmax(0,1fr));gap:8px;align-items:start;width:100%}
    .home-screen .bot-list>.bot-card{min-width:0;grid-column:auto!important;grid-row:auto}
    .home-screen .bot-list>.empty-search{grid-column:1/-1}
    .bot-card.dragging{opacity:.78;transform:scale(.985);border-color:#3b82f6;box-shadow:0 14px 32px rgba(0,0,0,.35),0 0 0 1px rgba(59,130,246,.22);z-index:50;cursor:grabbing!important}
    .bot-card.drag-target{border-color:#4b8df7!important;box-shadow:0 0 0 2px rgba(59,130,246,.18)}
    .bot-card.reorder-ready{touch-action:pan-y;user-select:none;-webkit-user-select:none}
    .bot-card.dragging,.bot-card.dragging *{touch-action:none!important}
    .bot-action.pin-action{color:#79a9ff}.bot-action.pin-action:hover{background:var(--blue-bg);color:#9bbcff}.bot-action.pin-action svg{transition:transform .18s}.bot-action.pin-action:hover svg{transform:rotate(-10deg) translateY(-1px)}
    .action-btn svg{transition:transform .22s cubic-bezier(.2,.8,.2,1),filter .22s}.action-btn[data-action="restart"]:hover svg,.action-btn[data-action="reinstall"]:hover svg{transform:rotate(180deg)}
    .action-btn[data-action="delete"] svg polyline{transform-box:fill-box;transform-origin:center;transition:transform .22s}.action-btn[data-action="delete"]:hover svg polyline{transform:rotate(-8deg) translateY(-1px)}.action-btn[data-action="stop"]:hover svg{transform:scale(.84)}.action-btn[data-action="start"]:hover svg{transform:translateX(2px) scale(1.06)}
    .layout-setting-input{width:54px;height:32px;border:1px solid var(--border);border-radius:9px;background:var(--bg-elevated);color:var(--text);font:600 13px var(--font-mono);text-align:center;outline:none}.layout-setting-input:focus{border-color:#315f9e;box-shadow:0 0 0 3px rgba(59,130,246,.08)}
    .layout-setting-hint{font-size:10px;color:var(--text-faint);padding:9px 15px 12px;border-top:1px solid var(--border-soft)}
    @media(max-width:600px){.home-screen .bot-list{grid-template-columns:repeat(var(--bot-columns,1),minmax(0,1fr))}.home-screen .bot-list[data-columns="2"] .bot-card-name{font-size:13px}.home-screen .bot-list[data-columns="2"] .bot-card-meters{grid-template-columns:1fr;gap:7px}.home-screen .bot-list[data-columns="2"] .bot-card-foot{font-size:8px}.home-screen .bot-list[data-columns="3"] .bot-card-meters,.home-screen .bot-list[data-columns="4"] .bot-card-meters{grid-template-columns:1fr}}
  `;
  function injectStyle(){let s=document.getElementById('dhost-enhancements-style');if(!s){s=document.createElement('style');s.id='dhost-enhancements-style';document.head.appendChild(s)}s.textContent=STYLE}
  function currentOrder(){return Array.isArray(order)?order:[]}
  function sortState(){if(!Array.isArray(window.STATE?.bots))return;const pos=new Map(currentOrder().map((n,i)=>[n,i]));const list=STATE.bots.slice().sort((a,b)=>{const ap=pinned.includes(a.name),bp=pinned.includes(b.name);if(ap!==bp)return ap?-1:1;return(pos.get(a.name)??999999)-(pos.get(b.name)??999999)});STATE.bots.splice(0,STATE.bots.length,...list)}
  function saveOrderFromCards(){const names=[...document.querySelectorAll('.bot-list>.bot-card')].map(c=>c.dataset.bot).filter(Boolean);if(!names.length)return;const known=new Set(names);order=[...names,...currentOrder().filter(n=>!known.has(n))];write(ORDER_KEY,order);if(Array.isArray(STATE?.bots)){const map=new Map(STATE.bots.map(b=>[b.name,b]));const reordered=order.map(n=>map.get(n)).filter(Boolean);const rest=STATE.bots.filter(b=>!known.has(b.name));STATE.bots.splice(0,STATE.bots.length,...reordered,...rest)}}
  function applyLayout(){document.querySelectorAll('.home-screen .bot-list').forEach(list=>{list.style.setProperty('--bot-columns',String(columns));list.dataset.columns=String(columns)})}
  function addPinMenus(){document.querySelectorAll('.bot-actions').forEach(menu=>{const card=menu.closest('.bot-card');const name=card?.dataset.bot||menu.querySelector('[data-menu-name]')?.dataset.menuName;if(!name||menu.querySelector('.pin-action'))return;const b=document.createElement('button');b.type='button';b.className='bot-action pin-action';b.innerHTML=(pinned.includes(name)?PIN_OFF:PIN)+'<span>'+(pinned.includes(name)?'Открепить':'Закрепить')+'</span>';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();pinned=pinned.includes(name)?pinned.filter(n=>n!==name):[...pinned.filter(n=>n!==name),name];write(PIN_KEY,pinned);if(window.DHOST_UI)DHOST_UI.menu=null;sortState();render()});menu.insertBefore(b,menu.firstChild)})}
  function addSettings(){if(typeof window.currentScreen!=='function'||currentScreen()!=='settings'||document.getElementById('row-columns'))return;const cards=document.querySelectorAll('.list-card'),target=cards[cards.length-1];if(!target)return;const section=document.createElement('div');section.className='section-label';section.textContent=LANG==='en'?'Layout':'Интерфейс';const card=document.createElement('div');card.className='list-card';card.innerHTML='<div class="list-row" id="row-columns"><div class="list-row-label">В ряд</div><input id="layout-columns" class="layout-setting-input" type="number" min="1" max="4" step="1" value="'+columns+'"></div><div class="layout-setting-hint">Количество юзерботов в одной строке.</div>';target.after(section,card);const input=card.querySelector('#layout-columns');input.addEventListener('change',()=>{columns=Math.max(1,Math.min(4,Number(input.value)||1));input.value=columns;write(COL_KEY,columns);render()})}
  function clearLongPress(){if(longPressTimer){clearTimeout(longPressTimer);longPressTimer=null}}
  function endDrag(){if(!drag)return;const item=drag.card;item.classList.remove('dragging');document.querySelectorAll('.drag-target').forEach(x=>x.classList.remove('drag-target'));document.body.style.userSelect='';document.body.style.webkitUserSelect='';if(item.releasePointerCapture&&drag.pointerId!=null){try{item.releasePointerCapture(drag.pointerId)}catch(_){}}saveOrderFromCards();drag=null;suppressClickUntil=Date.now()+250;setTimeout(()=>render(),30)}
  function moveDragged(x,y){if(!drag)return;const list=drag.list,target=document.elementFromPoint(x,y)?.closest('.bot-card');if(!target||target===drag.card||!list.contains(target))return;document.querySelectorAll('.drag-target').forEach(el=>el.classList.remove('drag-target'));target.classList.add('drag-target');const r=target.getBoundingClientRect();const before=columns===1?y<r.top+r.height/2:x<r.left+r.width/2;if(before){if(target.previousElementSibling!==drag.card)target.before(drag.card)}else{if(target.nextElementSibling!==drag.card)target.after(drag.card)}}
  function beginDrag(card,e){clearLongPress();const list=card.closest('.bot-list');if(!list)return;drag={card,list,pointerId:e.pointerId};card.classList.add('dragging');document.body.style.userSelect='none';document.body.style.webkitUserSelect='none';try{card.setPointerCapture(e.pointerId)}catch(_){}if(typeof window.haptic==='function')haptic('medium')}
  function setupDrag(){document.querySelectorAll('.bot-list>.bot-card').forEach(card=>{if(card.dataset.dragReady==='2')return;card.dataset.dragReady='2';card.classList.add('reorder-ready');let downX=0,downY=0;card.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;if(e.target.closest('button,.bot-actions,input,.search-box'))return;downX=e.clientX;downY=e.clientY;clearLongPress();longPressTimer=setTimeout(()=>beginDrag(card,e),420)});card.addEventListener('pointermove',e=>{if(!drag){if(Math.hypot(e.clientX-downX,e.clientY-downY)>12)clearLongPress();return}e.preventDefault();moveDragged(e.clientX,e.clientY)});card.addEventListener('pointerup',e=>{clearLongPress();if(drag?.card===card){e.preventDefault();endDrag()}});card.addEventListener('pointercancel',()=>{clearLongPress();if(drag?.card===card)endDrag()});card.addEventListener('lostpointercapture',()=>{clearLongPress();if(drag?.card===card)endDrag()})})}
  function patchRender(){if(window.__DHOST_ENHANCED_RENDER||typeof window.render!=='function')return;const original=window.render;window.render=function(){sortState();original();requestAnimationFrame(()=>{applyLayout();addPinMenus();addSettings();setupDrag()})};window.__DHOST_ENHANCED_RENDER=true}
  document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopPropagation()}},true);
  injectStyle();patchRender();const boot=()=>{patchRender();applyLayout();addPinMenus();addSettings();setupDrag()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else requestAnimationFrame(boot)
})();