/* DHost UX: single source for adaptive bot grid and reorder mode. */
(() => {
  const ORDER_KEY='dhost.botOrder.v5', PIN_KEY='dhost.botPinned.v4', COL_KEY='dhost.botColumns.v5';
  const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch(_){return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
  let order=Array.isArray(read(ORDER_KEY,null))?read(ORDER_KEY,[]):(Array.isArray(read('dhost.botOrder.v4',null))?read('dhost.botOrder.v4',[]):[]);
  let pinned=Array.isArray(read(PIN_KEY,null))?read(PIN_KEY,[]):(Array.isArray(read('dhost.botPinned.v3',null))?read('dhost.botPinned.v3',[]):[]);
  let columns=Math.max(1,Math.min(4,Number(read(COL_KEY,read('dhost.botColumns.v4',1)))||1));
  let reorderMode=false,draftOrder=[],originalOrder=[],drag=null;
  const PIN='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m14 4 6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/><path d="M12 12 5 5l4-4 7 7"/></svg>';
  const UNPIN='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m4 4 16 16"/><path d="M14 4l6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/></svg>';
  const DRAG='<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="8" cy="6" r="1.6"/><circle cx="16" cy="6" r="1.6"/><circle cx="8" cy="12" r="1.6"/><circle cx="16" cy="12" r="1.6"/><circle cx="8" cy="18" r="1.6"/><circle cx="16" cy="18" r="1.6"/></svg>';
  const CHECK='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4 4L19 6"/></svg>';
  const X='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 7l10 10M17 7 7 17"/></svg>';
  const STYLE=`
  .home-screen .bot-list{display:grid!important;grid-template-columns:repeat(var(--grid-columns,1),minmax(0,1fr));gap:8px;align-items:start;width:100%}
  .home-screen .bot-list>.bot-card{min-width:0;grid-column:auto!important;grid-row:auto;container-type:inline-size;overflow:hidden}
  .home-screen .bot-list>.empty-search{grid-column:1/-1}
  .home-screen .bot-list>.bot-card .bot-card-top{gap:clamp(4px,2.5cqw,9px)}
  .home-screen .bot-list>.bot-card .bot-card-name{font-size:clamp(8px,11cqw,15px);line-height:1.15}
  .home-screen .bot-list>.bot-card .bot-card-unit{font-size:clamp(7px,7.5cqw,10px)}
  .home-screen .bot-list>.bot-card .status-pill{font-size:clamp(7px,7.8cqw,10.5px);padding:clamp(3px,3.8cqw,5px) clamp(4px,5.8cqw,9px);gap:clamp(3px,3.5cqw,6px);max-width:48%;overflow:hidden;text-overflow:ellipsis}
  .home-screen .bot-list>.bot-card .status-pill .status-dot{width:clamp(4px,5cqw,6px);height:clamp(4px,5cqw,6px)}
  .home-screen .bot-list>.bot-card .bot-card-meters{gap:clamp(5px,7cqw,10px);margin-top:clamp(8px,10cqw,14px)}
  .home-screen .bot-list>.bot-card .meter-label{font-size:clamp(6.5px,7.2cqw,10px);min-width:0}
  .home-screen .bot-list>.bot-card .meter-label b{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .home-screen .bot-list>.bot-card .bot-card-foot{font-size:clamp(6.5px,7.2cqw,10px);gap:4px;margin-top:clamp(7px,9cqw,12px)}
  .home-screen .bot-list>.bot-card .bot-card-foot span{min-width:0}
  .layout-setting-row{cursor:pointer!important}.layout-setting-row:active{transform:scale(.995);background:var(--bg-card-hover)}
  .layout-setting-value{margin-left:auto;display:flex;align-items:center;gap:7px;color:var(--text-dim);font:600 12px var(--font-mono)}.layout-setting-value svg{width:15px;height:15px;color:var(--text-faint)}
  .layout-order-row{width:100%;justify-content:flex-start!important}.layout-order-row .list-row-label{font-weight:600;flex:1;text-align:left}.layout-order-row .layout-setting-value{margin-left:auto;flex:none}
  .reorder-screen{padding:0 0 18px;gap:10px;min-height:calc(100dvh - 70px)}
  .reorder-topbar{display:flex;align-items:center;gap:9px;padding:0 2px 7px}.reorder-title-wrap{min-width:0;flex:1}.reorder-title{font:700 16px var(--font-ui);letter-spacing:-.02em}.reorder-sub{font-size:9px;color:var(--text-faint);margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .reorder-back,.reorder-check{width:36px;height:36px;min-width:36px;border-radius:11px;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:transform .15s;flex:none}.reorder-back{border:1px solid rgba(255,102,85,.28);background:var(--err-bg);color:var(--err)}.reorder-check{border:1px solid rgba(53,208,127,.28);background:var(--ok-bg);color:var(--ok)}.reorder-back:active,.reorder-check:active{transform:scale(.9)}.reorder-back svg,.reorder-check svg{width:18px;height:18px}
  .reorder-grid{display:grid;grid-template-columns:repeat(var(--grid-columns,1),minmax(0,1fr));gap:8px;width:100%;align-items:start}
  .reorder-card{position:relative;min-width:0;padding:clamp(8px,2.8vw,13px);border:1px solid var(--border);border-radius:15px;background:var(--bg-card);transition:transform .16s,border-color .16s,box-shadow .16s,opacity .16s;touch-action:none;user-select:none;-webkit-user-select:none;cursor:grab;overflow:hidden}.reorder-card:active{cursor:grabbing}.reorder-card.is-dragging{opacity:.08}.reorder-card.drag-over{border-color:#4b8df7;box-shadow:0 0 0 2px rgba(59,130,246,.13)}
  .reorder-card-ghost{position:fixed!important;z-index:10000!important;pointer-events:none!important;margin:0!important;opacity:.98!important;transform:scale(1.035) rotate(1deg)!important;border-color:#4b8df7!important;box-shadow:0 18px 42px rgba(0,0,0,.5),0 0 0 2px rgba(59,130,246,.18)!important}
  .reorder-card-head{display:flex;align-items:center;gap:6px;min-width:0}.reorder-name{font:700 clamp(9px,3.1vw,14px) var(--font-ui);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;flex:1}.reorder-status{margin-left:auto;min-width:0;overflow:hidden}.reorder-status .status-pill{font-size:clamp(7px,2.2vw,10.5px);padding:4px 6px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.reorder-handle{width:27px;height:27px;min-width:27px;border:0;border-radius:8px;background:rgba(255,255,255,.045);color:var(--text-faint);display:flex;align-items:center;justify-content:center}.reorder-handle svg{width:15px;height:15px}
  .reorder-card-meta{margin-top:9px;font:500 clamp(7px,2.2vw,9px) var(--font-mono);color:var(--text-faint);display:flex;justify-content:space-between;gap:5px;min-width:0}.reorder-card-meta span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.reorder-card-meta span:last-child{color:var(--text-dim)}
  .reorder-save-sheet{position:fixed;inset:0;z-index:11000;background:rgba(4,7,10,.68);backdrop-filter:blur(7px);display:flex;align-items:flex-end;justify-content:center;padding:12px}.reorder-save-dialog{width:min(420px,100%);padding:17px;border:1px solid var(--border);border-radius:17px;background:var(--bg-card);box-shadow:0 20px 55px rgba(0,0,0,.5);animation:reorderSheetIn .16s ease-out}.reorder-save-title{font:700 15px var(--font-ui)}.reorder-save-text{font-size:10px;color:var(--text-faint);margin-top:5px}.reorder-save-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.reorder-save-actions button{height:44px;border-radius:11px;border:1px solid var(--border);font:700 11px var(--font-ui);cursor:pointer;display:flex;align-items:center;justify-content:center;gap:7px}.reorder-save-actions svg{width:17px;height:17px}.reorder-save-actions .save{background:var(--ok-bg);border-color:rgba(53,208,127,.28);color:var(--ok)}.reorder-save-actions .discard{background:var(--err-bg);border-color:rgba(255,102,85,.28);color:var(--err)}
  @keyframes reorderSheetIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
  `;
  function inject(){let s=document.getElementById('dhost-enhancements-v2-style');if(!s){s=document.createElement('style');s.id='dhost-enhancements-v2-style';document.head.appendChild(s)}s.textContent=STYLE}
  function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
  function sortState(list=STATE?.bots){if(!Array.isArray(list))return;const pos=new Map(order.map((n,i)=>[n,i]));list.sort((a,b)=>{const ap=pinned.includes(a.name),bp=pinned.includes(b.name);if(ap!==bp)return ap?-1:1;return(pos.get(a.name)??999999)-(pos.get(b.name)??999999)})}
  function normalizeOrder(names){const next=[];names.forEach(n=>{if(n&&!next.includes(n))next.push(n)});order.forEach(n=>{if(!next.includes(n))next.push(n)});(STATE?.bots||[]).forEach(b=>{if(!next.includes(b.name))next.push(b.name)});return next}
  function effectiveColumns(count){return Math.max(1,Math.min(columns,Math.max(1,count)))}
  function applyLayout(){document.querySelectorAll('.home-screen .bot-list').forEach(list=>{const count=list.querySelectorAll(':scope > .bot-card').length||STATE?.bots?.length||1;list.style.setProperty('--grid-columns',String(effectiveColumns(count)));list.dataset.columns=String(effectiveColumns(count))})}
  function addPinMenus(){document.querySelectorAll('.bot-actions').forEach(menu=>{const card=menu.closest('.bot-card');const name=card?.dataset.bot||menu.querySelector('[data-menu-name]')?.dataset.menuName;if(!name||menu.querySelector('.pin-action'))return;const b=document.createElement('button');b.type='button';b.className='bot-action pin-action';b.innerHTML=(pinned.includes(name)?UNPIN:PIN)+'<span>'+(pinned.includes(name)?'Открепить':'Закрепить')+'</span>';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();pinned=pinned.includes(name)?pinned.filter(n=>n!==name):[...pinned,name];write(PIN_KEY,pinned);if(window.DHOST_UI)DHOST_UI.menu=null;sortState();render()});menu.insertBefore(b,menu.firstChild)})}
  function addLayoutRow(){if(typeof currentScreen!=='function'||currentScreen()!=='settings'||document.getElementById('dhost-order-row'))return;if(!STATE?.bots||STATE.bots.length<2)return;const cards=[...document.querySelectorAll('.list-card')],target=cards[cards.length-1];if(!target)return;const section=document.createElement('div');section.className='section-label';section.textContent=LANG==='en'?'Interface':'Интерфейс';const card=document.createElement('div');card.className='list-card';card.innerHTML='<button type="button" class="list-row layout-setting-row layout-order-row" id="dhost-order-row"><div class="list-row-label">Изменить порядок</div><div class="layout-setting-value"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg></div></button>';target.after(section,card);card.querySelector('#dhost-order-row').addEventListener('click',openReorderScreen)}
  function reorderCards(){return(draftOrder||[]).map(n=>STATE.bots.find(b=>b.name===n)).filter(Boolean)}
  function reorderMarkup(){const bots=reorderCards(),cols=effectiveColumns(bots.length),cards=bots.map(b=>`<div class="reorder-card" data-reorder-bot="${esc(b.name)}"><div class="reorder-card-head"><div class="reorder-name">${esc(b.name)}</div><div class="reorder-status">${statusPill(b.status)}</div><div class="reorder-handle" aria-hidden="true">${DRAG}</div></div><div class="reorder-card-meta"><span>${t('cpu')} ${Number(b.cpu_percent||0).toFixed(1)}%</span><span>${t('ram')} ${Math.round(Number(b.ram_used_mb)||0)}/${Math.round(Number(b.ram_limit_mb)||0)}MB</span></div></div>`).join('');return`<div class="screen reorder-screen"><div class="reorder-topbar"><button class="reorder-back" id="reorder-cancel" type="button" aria-label="Отмена">${X}</button><div class="reorder-title-wrap"><div class="reorder-title">Порядок юзерботов</div><div class="reorder-sub">Нажмите и перетащите любую часть карточки</div></div><button class="reorder-check" id="reorder-done" type="button" aria-label="Сохранить">${CHECK}</button></div><div class="reorder-grid" id="reorder-grid" style="--grid-columns:${cols}">${cards}</div></div>`}
  function openReorderScreen(){if(!STATE?.bots?.length||STATE.bots.length<2)return;sortState();draftOrder=STATE.bots.map(b=>b.name);originalOrder=[...draftOrder];reorderMode=true;document.getElementById('app').innerHTML=reorderMarkup();wireReorder();haptic?.('light')}
  function dirty(){return draftOrder.length!==originalOrder.length||draftOrder.some((v,i)=>v!==originalOrder[i])}
  function finishReorder(){reorderMode=false;drag=null;draftOrder=[];originalOrder=[];render()}
  function closeReorder(){dirty()?showSaveSheet():finishReorder()}
  function rerenderReorder(){if(!reorderMode)return;document.getElementById('app').innerHTML=reorderMarkup();wireReorder()}
  function startDrag(card,e){if(!reorderMode||drag)return;const grid=document.getElementById('reorder-grid');if(!grid)return;const r=card.getBoundingClientRect(),ph=document.createElement('div');ph.className='reorder-card';ph.style.visibility='hidden';ph.style.width=r.width+'px';ph.style.height=r.height+'px';card.after(ph);card.classList.add('is-dragging');const ghost=card.cloneNode(true);ghost.classList.add('reorder-card-ghost');ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';ghost.style.left=r.left+'px';ghost.style.top=r.top+'px';document.body.appendChild(ghost);drag={card,grid,ph,ghost,ox:e.clientX-r.left,oy:e.clientY-r.top};try{card.setPointerCapture(e.pointerId)}catch(_){}moveDrag(e.clientX,e.clientY)}
  function moveDrag(x,y){if(!drag)return;const d=drag;d.ghost.style.left=(x-d.ox)+'px';d.ghost.style.top=(y-d.oy)+'px';const target=document.elementFromPoint(x,y)?.closest('.reorder-card');if(!target||target===d.card||target===d.ph||!d.grid.contains(target))return;document.querySelectorAll('.reorder-card.drag-over').forEach(c=>c.classList.remove('drag-over'));target.classList.add('drag-over');const r=target.getBoundingClientRect(),before=effectiveColumns(draftOrder.length)>1?(x<r.left+r.width/2):(y<r.top+r.height/2);before?target.before(d.ph):target.after(d.ph)}
  function finishDrag(){if(!drag)return;const d=drag;drag=null;d.card.classList.remove('is-dragging');d.ph.replaceWith(d.card);d.ghost.remove();document.querySelectorAll('.reorder-card.drag-over').forEach(c=>c.classList.remove('drag-over'));draftOrder=[...document.querySelectorAll('#reorder-grid .reorder-card')].map(c=>c.dataset.reorderBot).filter(Boolean);rerenderReorder();haptic?.('light')}
  function bindCards(){document.querySelectorAll('#reorder-grid .reorder-card').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';let start=null;card.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;e.preventDefault();start={x:e.clientX,y:e.clientY};try{card.setPointerCapture(e.pointerId)}catch(_){} });card.addEventListener('pointermove',e=>{if(drag){e.preventDefault();moveDrag(e.clientX,e.clientY);return}if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>=6){start=null;try{card.releasePointerCapture(e.pointerId)}catch(_){}startDrag(card,e)}});card.addEventListener('pointerup',e=>{if(drag?.card===card){e.preventDefault();finishDrag()}start=null});card.addEventListener('pointercancel',()=>{if(drag?.card===card)finishDrag();start=null});card.addEventListener('lostpointercapture',()=>{if(drag?.card===card)finishDrag();start=null})})}
  function wireReorder(){document.getElementById('reorder-cancel')?.addEventListener('click',closeReorder);document.getElementById('reorder-done')?.addEventListener('click',saveDraft);bindCards()}
  function saveDraft(){if(!reorderMode)return;order=normalizeOrder(draftOrder);write(ORDER_KEY,order);sortState();finishReorder();haptic?.('success')}
  function showSaveSheet(){if(document.querySelector('.reorder-save-sheet'))return;const sheet=document.createElement('div');sheet.className='reorder-save-sheet';sheet.innerHTML=`<div class="reorder-save-dialog"><div class="reorder-save-title">Сохранить изменения?</div><div class="reorder-save-text">Вы изменили порядок юзерботов. Сохранить новый порядок?</div><div class="reorder-save-actions"><button class="discard" type="button">${X}<span>Не сохранять</span></button><button class="save" type="button">${CHECK}<span>Сохранить</span></button></div></div>`;sheet.querySelector('.save').addEventListener('click',()=>{sheet.remove();saveDraft()});sheet.querySelector('.discard').addEventListener('click',()=>{sheet.remove();finishReorder();haptic?.('warning')});document.body.appendChild(sheet)}
  function patchRender(){if(window.__DHOST_ENHANCED_RENDER5||typeof window.render!=='function')return;const original=window.render;window.render=function(){if(reorderMode)return;sortState();original();requestAnimationFrame(()=>{applyLayout();addPinMenus();addLayoutRow()})};window.__DHOST_ENHANCED_RENDER5=true}
  document.addEventListener('click',e=>{if(reorderMode)return;if(document.querySelector('.bot-actions')&&!e.target.closest('.bot-actions')&&!e.target.closest('.bot-menu-button')){document.querySelectorAll('.bot-actions').forEach(m=>m.remove());if(window.DHOST_UI)window.DHOST_UI.menu=null}},false);
  inject();patchRender();const boot=()=>{patchRender();applyLayout();addPinMenus();addLayoutRow()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else requestAnimationFrame(boot);
})();