/* DHost UX enhancements: pinned bots, true grid, Android-like long-press reorder. */
(() => {
  const ORDER_KEY='dhost.botOrder.v3', PIN_KEY='dhost.botPinned.v3', COL_KEY='dhost.botColumns.v3';
  const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch(_){return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
  let order=Array.isArray(read(ORDER_KEY,null))?read(ORDER_KEY,[]):(Array.isArray(read('dhost.botOrder.v2',null))?read('dhost.botOrder.v2',[]):read('dhost.botOrder.v1',[]));
  let pinned=Array.isArray(read(PIN_KEY,null))?read(PIN_KEY,[]):(Array.isArray(read('dhost.botPinned.v2',null))?read('dhost.botPinned.v2',[]):read('dhost.botPinned.v1',[]));
  let columns=Math.max(1,Math.min(4,Number(read(COL_KEY,read('dhost.botColumns.v2',read('dhost.botColumns.v1',1))))||1));
  let pressTimer=null,drag=null,suppressClickUntil=0;
  const PIN='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m14 4 6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/><path d="M12 12 5 5l4-4 7 7"/></svg>';
  const PIN_OFF='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m4 4 16 16"/><path d="M14 4l6 6"/><path d="M17 7 7 17"/><path d="m5 19 4-4"/></svg>';
  const STYLE=`
    .home-screen .bot-list{display:grid!important;grid-template-columns:repeat(var(--bot-columns,1),minmax(0,1fr));gap:8px;align-items:start;width:100%}
    .home-screen .bot-list>.bot-card{min-width:0;grid-column:auto!important;grid-row:auto;will-change:transform}
    .home-screen .bot-list>.empty-search{grid-column:1/-1}
    .bot-card.reorder-ready{touch-action:pan-y;user-select:none;-webkit-user-select:none}
    .bot-card.press-armed{transform:scale(.985);border-color:#315f9e!important;box-shadow:0 0 0 2px rgba(59,130,246,.12)}
    .bot-card.drag-source{visibility:hidden!important}
    .dhost-drag-ghost{position:fixed!important;z-index:9999!important;pointer-events:none!important;margin:0!important;opacity:.97!important;transform:scale(1.045) rotate(1deg)!important;border-color:#4b8df7!important;box-shadow:0 20px 45px rgba(0,0,0,.48),0 0 0 2px rgba(59,130,246,.22)!important;transition:transform .12s cubic-bezier(.2,.8,.2,1),box-shadow .12s}
    .dhost-drag-placeholder{border:1px dashed rgba(75,141,247,.55)!important;background:rgba(59,130,246,.055)!important;box-shadow:inset 0 0 0 1px rgba(59,130,246,.08);border-radius:15px;min-height:80px;transition:all .12s cubic-bezier(.2,.8,.2,1)}
    .bot-card.drag-target{border-color:#4b8df7!important;box-shadow:0 0 0 2px rgba(59,130,246,.14)!important}
    .bot-actions-close{display:none!important}
    .bot-action.pin-action{color:#79a9ff}.bot-action.pin-action:hover{background:var(--blue-bg);color:#9bbcff}.bot-action.pin-action svg{transition:transform .18s}.bot-action.pin-action:hover svg{transform:rotate(-10deg) translateY(-1px)}
    .action-btn svg{transition:transform .22s cubic-bezier(.2,.8,.2,1),filter .22s}.action-btn[data-action="restart"]:hover svg,.action-btn[data-action="reinstall"]:hover svg{transform:rotate(180deg)}
    .action-btn[data-action="delete"] svg polyline{transform-box:fill-box;transform-origin:center;transition:transform .22s}.action-btn[data-action="delete"]:hover svg polyline{transform:rotate(-8deg) translateY(-1px)}.action-btn[data-action="stop"]:hover svg{transform:scale(.84)}.action-btn[data-action="start"]:hover svg{transform:translateX(2px) scale(1.06)}
    .layout-setting-input{width:54px;height:32px;border:1px solid var(--border);border-radius:9px;background:var(--bg-elevated);color:var(--text);font:600 13px var(--font-mono);text-align:center;outline:none}.layout-setting-input:focus{border-color:#315f9e;box-shadow:0 0 0 3px rgba(59,130,246,.08)}
    .layout-setting-hint{font-size:10px;color:var(--text-faint);padding:9px 15px 12px;border-top:1px solid var(--border-soft)}
    @media(max-width:600px){.home-screen .bot-list{grid-template-columns:repeat(var(--bot-columns,1),minmax(0,1fr))}.home-screen .bot-list[data-columns="2"] .bot-card-name{font-size:13px}.home-screen .bot-list[data-columns="2"] .bot-card-meters{grid-template-columns:1fr;gap:7px}.home-screen .bot-list[data-columns="2"] .bot-card-foot{font-size:8px}.home-screen .bot-list[data-columns="3"] .bot-card-meters,.home-screen .bot-list[data-columns="4"] .bot-card-meters{grid-template-columns:1fr}}
  `;
  function inject(){let s=document.getElementById('dhost-enhancements-style');if(!s){s=document.createElement('style');s.id='dhost-enhancements-style';document.head.appendChild(s)}s.textContent=STYLE}
  function sortState(){if(!Array.isArray(window.STATE?.bots))return;const pos=new Map(order.map((n,i)=>[n,i]));const list=STATE.bots.slice().sort((a,b)=>{const ap=pinned.includes(a.name),bp=pinned.includes(b.name);if(ap!==bp)return ap?-1:1;return(pos.get(a.name)??999999)-(pos.get(b.name)??999999)});STATE.bots.splice(0,STATE.bots.length,...list)}
  function saveOrder(){const visible=[...document.querySelectorAll('.bot-list>.bot-card')].map(c=>c.dataset.bot).filter(Boolean);if(!visible.length)return;const next=[];visible.forEach(n=>{if(!next.includes(n))next.push(n)});order.forEach(n=>{if(!next.includes(n))next.push(n)});(STATE.bots||[]).forEach(b=>{if(!next.includes(b.name))next.push(b.name)});order=next;write(ORDER_KEY,order);sortState()}
  function applyLayout(){document.querySelectorAll('.home-screen .bot-list').forEach(list=>{list.style.setProperty('--bot-columns',String(columns));list.dataset.columns=String(columns)})}
  function addPinMenus(){document.querySelectorAll('.bot-actions').forEach(menu=>{const card=menu.closest('.bot-card');const name=card?.dataset.bot||menu.querySelector('[data-menu-name]')?.dataset.menuName;if(!name||menu.querySelector('.pin-action'))return;const b=document.createElement('button');b.type='button';b.className='bot-action pin-action';b.innerHTML=(pinned.includes(name)?PIN_OFF:PIN)+'<span>'+(pinned.includes(name)?'Открепить':'Закрепить')+'</span>';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();pinned=pinned.includes(name)?pinned.filter(n=>n!==name):[...pinned,name];write(PIN_KEY,pinned);if(window.DHOST_UI)DHOST_UI.menu=null;sortState();render()});menu.insertBefore(b,menu.firstChild)})}
  function addSettings(){if(typeof window.currentScreen!=='function'||currentScreen()!=='settings'||document.getElementById('row-columns'))return;const cards=document.querySelectorAll('.list-card'),target=cards[cards.length-1];if(!target)return;const section=document.createElement('div');section.className='section-label';section.textContent=LANG==='en'?'Layout':'Интерфейс';const card=document.createElement('div');card.className='list-card';card.innerHTML='<div class="list-row" id="row-columns"><div class="list-row-label">В ряд</div><input id="layout-columns" class="layout-setting-input" type="number" min="1" max="4" step="1" value="'+columns+'"></div><div class="layout-setting-hint">Количество юзерботов в одной строке.</div>';target.after(section,card);const input=card.querySelector('#layout-columns');input.addEventListener('change',()=>{columns=Math.max(1,Math.min(4,Number(input.value)||1));input.value=columns;write(COL_KEY,columns);render()})}
  function clearPress(){if(pressTimer){clearTimeout(pressTimer);pressTimer=null}}
  function stopDrag(){if(!drag)return;const d=drag;drag=null;clearPress();d.card.classList.remove('drag-source','press-armed');d.placeholder.replaceWith(d.card);d.ghost.remove();document.querySelectorAll('.drag-target').forEach(x=>x.classList.remove('drag-target'));document.body.classList.remove('dhost-dragging');document.body.style.userSelect='';document.body.style.webkitUserSelect='';document.body.style.touchAction='';if(d.card.releasePointerCapture){try{d.card.releasePointerCapture(d.pointerId)}catch(_){}}saveOrder();suppressClickUntil=Date.now()+300;if(typeof haptic==='function')haptic('light')}
  function moveGhost(x,y){if(!drag)return;const d=drag;d.ghost.style.left=(x-d.offsetX)+'px';d.ghost.style.top=(y-d.offsetY)+'px';const el=document.elementFromPoint(x,y);const target=el?.closest('.bot-card');if(!target||target===d.card||!d.list.contains(target)){document.querySelectorAll('.drag-target').forEach(x=>x.classList.remove('drag-target'));return}document.querySelectorAll('.drag-target').forEach(x=>x.classList.remove('drag-target'));target.classList.add('drag-target');const r=target.getBoundingClientRect();const before=columns===1?y<r.top+r.height/2:(y<r.top+r.height/2||x<r.left+r.width/2);if(before){if(target!==d.placeholder&&target.previousElementSibling!==d.placeholder)target.before(d.placeholder)}else{if(target!==d.placeholder&&target.nextElementSibling!==d.placeholder)target.after(d.placeholder)}}
  function beginDrag(card,e){clearPress();if(UIStateBlocked())return;const list=card.closest('.bot-list');if(!list)return;const r=card.getBoundingClientRect();const ph=document.createElement('div');ph.className='dhost-drag-placeholder';ph.style.width=r.width+'px';ph.style.height=r.height+'px';card.parentNode.insertBefore(ph,card);card.classList.add('drag-source');const ghost=card.cloneNode(true);ghost.classList.add('dhost-drag-ghost');ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';ghost.style.left=r.left+'px';ghost.style.top=r.top+'px';document.body.appendChild(ghost);drag={card,list,placeholder:ph,ghost,pointerId:e.pointerId,offsetX:e.clientX-r.left,offsetY:e.clientY-r.top};document.body.classList.add('dhost-dragging');document.body.style.userSelect='none';document.body.style.webkitUserSelect='none';document.body.style.touchAction='none';try{card.setPointerCapture(e.pointerId)}catch(_){}if(typeof haptic==='function')haptic('medium');moveGhost(e.clientX,e.clientY)}
  function UIStateBlocked(){return !!(window.DHOST_UI?.query||'').trim()||!!(window.DHOST_UI?.filter&&window.DHOST_UI.filter!=='all')}
  function setupDrag(){document.querySelectorAll('.bot-list>.bot-card').forEach(card=>{if(card.dataset.dragReady==='4')return;card.dataset.dragReady='4';card.classList.add('reorder-ready');let sx=0,sy=0;card.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;if(e.target.closest('button,.bot-actions,input,.search-box'))return;sx=e.clientX;sy=e.clientY;clearPress();card.classList.remove('press-armed');pressTimer=setTimeout(()=>{card.classList.add('press-armed');beginDrag(card,e)},200)});card.addEventListener('pointermove',e=>{if(!drag){if(Math.hypot(e.clientX-sx,e.clientY-sy)>8)clearPress();return}e.preventDefault();moveGhost(e.clientX,e.clientY)});card.addEventListener('pointerup',e=>{clearPress();if(drag?.card===card){e.preventDefault();stopDrag()}});card.addEventListener('pointercancel',()=>{clearPress();if(drag?.card===card)stopDrag()});card.addEventListener('lostpointercapture',()=>{if(drag?.card===card)stopDrag()})})}
  function closeMenuDom(){document.querySelectorAll('.bot-actions').forEach(m=>m.remove());if(window.DHOST_UI)window.DHOST_UI.menu=null}
  function patchRender(){if(window.__DHOST_ENHANCED_RENDER3||typeof window.render!=='function')return;const original=window.render;window.render=function(){sortState();original();requestAnimationFrame(()=>{applyLayout();addPinMenus();addSettings();setupDrag()})};window.__DHOST_ENHANCED_RENDER3=true}
  document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopPropagation();return}if(document.querySelector('.bot-actions')&&!e.target.closest('.bot-actions')&&!e.target.closest('.bot-menu-button'))closeMenuDom()},false);
  inject();patchRender();const boot=()=>{patchRender();applyLayout();addPinMenus();addSettings();setupDrag()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else requestAnimationFrame(boot);
})();