/* DHost UI v2: real CPU/RAM sparklines, 3s polling, compact bot menus and micro-interactions. */
(() => {
  const UI = window.DHOST_UI || { query: "", filter: "all", menu: null, refreshing: false };
  window.DHOST_UI = UI;
  const HISTORY = window.DHOST_RESOURCE_HISTORY || new Map();
  window.DHOST_RESOURCE_HISTORY = HISTORY;
  const MAX_POINTS = 12;

  const X = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M6 6l12 12M18 6L6 18"/></svg>';
  const SEARCH = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>';
  const FILTER = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h16M7 12h10M10 18h4"/></svg>';
  const MORE = '<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="5" r="1.7"/><circle cx="12" cy="12" r="1.7"/><circle cx="12" cy="19" r="1.7"/></svg>';
  const CHART = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19V5M4 19h16"/><path d="m7 15 3-4 3 2 4-6"/></svg>';

  const STYLE = `
    .resource-wave,.summary-wave{display:none!important}
    .home-top-actions{display:flex;align-items:center;gap:7px}.home-top-action{width:36px;height:36px;min-width:36px;border-radius:11px;background:var(--bg-card);border:1px solid var(--border);color:var(--text-dim);display:flex;align-items:center;justify-content:center;cursor:pointer;transition:transform .16s cubic-bezier(.2,.8,.2,1),background .16s,border-color .16s,color .16s,box-shadow .16s}.home-top-action svg{width:18px;height:18px}.home-top-action:hover{color:var(--text);border-color:#34404a;background:var(--bg-card-hover)}.home-top-action:active{transform:scale(.9)}.home-top-action.primary{color:#fff;background:var(--blue);border-color:rgba(59,130,246,.5);box-shadow:0 5px 15px rgba(59,130,246,.16)}.home-top-action.primary:hover{background:var(--blue-hover);box-shadow:0 7px 20px rgba(59,130,246,.23)}.home-top-action.spinning svg{animation:spin .7s linear infinite}
    .topbar-home{padding-bottom:9px}.screen.home-screen{padding-top:2px;gap:10px}.summary{padding:13px 14px;border-radius:18px}.summary-count{font-size:22px}.summary-progress{height:4px;margin-top:10px}.summary-foot{margin-top:6px;font-size:9px}.summary-stats{grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.summary-stat{position:relative;min-height:54px;padding:9px;border-radius:12px;overflow:hidden;cursor:pointer;transition:transform .15s,border-color .15s,background .15s}.summary-stat:hover{border-color:#303941;background:var(--bg-card-hover)}.summary-stat:active{transform:scale(.97)}.summary-stat-head{display:flex;align-items:center;gap:7px}.summary-stat-value{font-size:14px}.summary-stat-label{font-size:9px;margin-top:3px}.summary-stat .status-wave{width:6px;height:6px;min-width:6px;border-radius:50%;display:inline-block;background:currentColor;box-shadow:0 0 8px currentColor;position:relative}.summary-stat .status-wave:before,.summary-stat .status-wave:after{content:"";position:absolute;inset:-4px;border:1px solid currentColor;border-radius:50%;opacity:0;animation:statusPulse 2.6s ease-out infinite}.summary-stat .status-wave:after{animation-delay:1.3s}.summary-stat.running{color:var(--ok)}.summary-stat.installing{color:var(--warn)}.summary-stat.error{color:var(--err)}.summary-stat .summary-stat-label{color:var(--text-faint)}@keyframes statusPulse{0%{transform:scale(.55);opacity:.65}72%,100%{transform:scale(2.1);opacity:0}}
    .search-row{gap:7px}.search-box{height:39px;border-radius:11px;padding:0 10px}.search-box svg{width:15px}.search-box input{font-size:12px}.search-clear{width:25px;height:25px;min-width:25px;border:0;border-radius:8px;background:transparent;color:var(--text-faint);display:flex;align-items:center;justify-content:center;cursor:pointer}.search-clear svg{width:14px}.search-clear:hover{color:var(--text)}.filter-button{width:39px;height:39px;min-width:39px;padding:0;display:flex;align-items:center;justify-content:center;border-radius:11px}.filter-button svg{width:17px;height:17px}.filter-button.active{color:#79a9ff;border-color:#315f9e;background:var(--blue-bg)}
    .filter-menu{display:flex;gap:6px;overflow:auto;padding:0 1px 1px}.filter-chip{border:1px solid var(--border);background:var(--bg-card);color:var(--text-dim);border-radius:99px;padding:7px 11px;font-size:10px;font-weight:600;white-space:nowrap;cursor:pointer;transition:.15s}.filter-chip.active{background:var(--blue-bg);border-color:#315f9e;color:#79a9ff}.filter-chip:active{transform:scale(.96)}
    .bot-list{gap:8px}.bot-card{position:relative;padding:12px 13px;border-radius:15px;cursor:pointer;transition:background .16s,border-color .16s,transform .12s,box-shadow .16s}.bot-card:hover{border-color:#303941;background:var(--bg-card-hover)}.bot-card:active{transform:scale(.993)}.bot-card-top{gap:8px}.bot-card-name{font-size:15px;letter-spacing:-.02em}.bot-card-unit{display:none}.bot-menu-button{width:28px;height:28px;min-width:28px;border:0;border-radius:9px;background:transparent;color:var(--text-faint);display:flex;align-items:center;justify-content:center;cursor:pointer;transition:.15s}.bot-menu-button svg{width:17px;height:17px}.bot-menu-button:hover{background:rgba(255,255,255,.05);color:var(--text)}.bot-menu-button:active{transform:scale(.86)}
    .bot-card-meters{gap:10px;margin-top:11px}.meter{gap:4px}.meter-label{font-size:9px}.meter-label b{font-weight:600}.meter-track{height:4px}.meter-spark{display:block;width:100%;height:24px;margin-top:1px;overflow:visible}.meter-spark path{fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 0 2px currentColor)}.meter-spark.cpu,.meter-spark.ram{color:var(--cyan)}.meter-spark.warn{color:var(--warn)}.meter-spark.err{color:var(--err)}.bot-card-foot{margin-top:8px;font-size:9px}.bot-card-foot span:first-child{display:none}.bot-card-foot span:last-child{margin-left:auto}
    .bot-actions{position:absolute;right:10px;top:43px;z-index:20;display:flex;flex-direction:column;gap:4px;padding:5px;background:#15191d;border:1px solid var(--border);border-radius:11px;box-shadow:0 12px 28px rgba(0,0,0,.42);animation:menuIn .14s ease-out}.bot-actions:before{content:"";position:absolute;right:9px;top:-5px;width:8px;height:8px;background:#15191d;border-left:1px solid var(--border);border-top:1px solid var(--border);transform:rotate(45deg)}@keyframes menuIn{from{opacity:0;transform:translateY(-4px) scale(.97)}to{opacity:1;transform:none}}.bot-action{display:flex;align-items:center;gap:7px;width:132px;padding:8px 9px;border:0;border-radius:8px;background:transparent;color:var(--text-dim);font:600 10px var(--font-ui);text-align:left;cursor:pointer;transition:transform .12s,background .12s,color .12s}.bot-action svg{width:14px;height:14px}.bot-action:hover{background:rgba(255,255,255,.055);color:var(--text)}.bot-action:active{transform:scale(.95)}.bot-action.danger{color:var(--err)}.bot-action.danger:hover{background:var(--err-bg)}
    .btn,.action-btn{transition:transform .16s cubic-bezier(.2,.8,.2,1),background .16s,border-color .16s,color .16s,box-shadow .16s}.btn:hover,.action-btn:hover{transform:translateY(-1px)}.btn:active,.action-btn:active{transform:scale(.97) translateY(0)}.action-btn:hover{border-color:#34404a;background:var(--bg-card-hover);box-shadow:0 5px 15px rgba(0,0,0,.16)}.action-btn.danger:hover{border-color:rgba(255,102,85,.35);background:var(--err-bg)}
    @media(max-width:360px){.home-top-action{width:33px;height:33px;min-width:33px}.summary-stats{gap:5px}.summary-stat{padding:8px}.bot-card{padding:11px 12px}}
  `;

  function installStyle(){if(document.getElementById("dhost-ui-v2-style"))return;const s=document.createElement("style");s.id="dhost-ui-v2-style";s.textContent=STYLE;document.head.appendChild(s)}
  function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function remember(){for(const b of STATE.bots){const cpu=Math.max(0,Math.min(Number(b.cpu_percent)||0,100));const ram=b.ram_limit_mb?Math.max(0,Math.min((Number(b.ram_used_mb)||0)/Number(b.ram_limit_mb)*100,100)):0;const h=HISTORY.get(b.name)||{cpu:[],ram:[]};if(h.cpu[h.cpu.length-1]!==cpu)h.cpu.push(cpu);if(h.ram[h.ram.length-1]!==ram)h.ram.push(ram);h.cpu=h.cpu.slice(-MAX_POINTS);h.ram=h.ram.slice(-MAX_POINTS);HISTORY.set(b.name,h)}}
  function spark(values,kind,pct){const a=values.length?values:[pct];const w=100,h=24;let pts=a.map((v,i)=>{const x=a.length===1?2:2+i/(a.length-1)*96;const y=22-(Math.max(0,Math.min(100,v))/100)*19;return [x,y]});if(pts.length===1)pts.push([98,pts[0][1]]);let d=`M ${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)}`;for(let i=1;i<pts.length;i++){const p=pts[i-1],q=pts[i],cx=(p[0]+q[0])/2;d+=` C ${cx.toFixed(1)} ${p[1].toFixed(1)}, ${cx.toFixed(1)} ${q[1].toFixed(1)}, ${q[0].toFixed(1)} ${q[1].toFixed(1)}`}const cls=pct>=(kind==="cpu"?85:90)?"err":pct>=(kind==="cpu"?65:75)?"warn":kind;return `<svg class="meter-spark ${cls}" viewBox="0 0 100 24" preserveAspectRatio="none" aria-hidden="true"><path d="${d}"/></svg>`}
  function filtered(){const q=UI.query.trim().toLowerCase();return STATE.bots.filter(b=>(!q||`${b.name} ${b.platform}`.toLowerCase().includes(q))&&(UI.filter==="all"||b.status===UI.filter))}
  function actionFor(b){return b.status==="running"?{action:"stop",label:t("stop"),icon:ICON.stop}:{action:"start",label:t("start"),icon:ICON.play}}

  window.renderHeader = function(screen){const meta=HEADER_META[screen]||HEADER_META.home;if(screen==="home")return `<div class="topbar topbar-home"><div class="topbar-title">${meta.title()}</div><div class="topbar-spacer"></div><div class="home-top-actions"><button class="home-top-action" id="btn-settings" title="Настройки">${ICON.settings}</button><button class="home-top-action" id="btn-refresh-top" title="Обновить">${ICON.refresh}</button><button class="home-top-action primary" id="btn-open-top" title="${t("installNew")}">${ICON.plus}</button></div></div>`;const showBack=NAV.stack.length>1;return `<div class="topbar">${showBack?`<div class="topbar-back" id="btn-back">${ICON.back}</div>`:""}<div><div class="topbar-title">${meta.title()}</div>${meta.sub()?`<div class="topbar-sub">${meta.sub()}</div>`:""}</div><div class="topbar-spacer"></div>${meta.action==="settings"?`<div class="topbar-action" id="btn-settings">${ICON.settings}</div>`:""}</div>`};

  window.screenHome = function(){
    installStyle();
    if(STATE.loading)return `<div class="screen home-screen"><div class="skel skel-card"></div><div class="skel skel-card"></div></div>`;
    if(!STATE.bots.length)return `<div class="gate"><div class="gate-icon">${ICON.server}</div><div class="gate-title">${t("emptyTitle")}</div><div class="gate-text">${t("emptyText")}</div><button class="btn btn-primary" id="btn-open-bot">${ICON.plus}${t("installNew")}</button></div>`;
    remember();
    const sub=STATE.subscription;const running=STATE.bots.filter(b=>b.status==="running").length;const errors=STATE.bots.filter(b=>b.status==="error").length;const installing=STATE.bots.filter(b=>b.status==="installing").length;const used=sub?.used_slots??STATE.bots.length;const max=sub?.max_slots??STATE.bots.length;const pct=max?Math.min(used/max*100,100):0;
    const cards=filtered().map(b=>{const cpu=Math.max(0,Math.min(Number(b.cpu_percent)||0,100));const rl=Number(b.ram_limit_mb)||0,ru=Number(b.ram_used_mb)||0,ram=rl?Math.min(ru/rl*100,100):0;const h=HISTORY.get(b.name)||{cpu:[cpu],ram:[ram]};const act=actionFor(b);const open=UI.menu===b.name;return `<div class="bot-card" data-bot="${esc(b.name)}"><div class="bot-card-top"><div class="bot-name-wrap"><div class="bot-card-name">${esc(b.name)}</div></div><div class="bot-card-spacer"></div>${statusPill(b.status)}<button class="bot-menu-button" data-menu-bot="${esc(b.name)}" aria-label="Меню">${MORE}</button></div><div class="bot-card-meters"><div class="meter"><div class="meter-label"><span>${t("cpu")}</span><b>${cpu.toFixed(1)}%</b></div>${spark(h.cpu,"cpu",cpu)}</div><div class="meter"><div class="meter-label"><span>${t("ram")}</span><b>${Math.round(ru)}/${Math.round(rl)}MB</b></div>${spark(h.ram,"ram",ram)}</div></div><div class="bot-card-foot"><span></span><span>${b.platform||"Server"} · ${fmtUptime(b.uptime_seconds)}</span></div>${open?`<div class="bot-actions"><button class="bot-action" data-menu-action="${act.action}" data-menu-name="${esc(b.name)}">${act.icon}${act.label}</button><button class="bot-action" data-menu-action="restart" data-menu-name="${esc(b.name)}">${ICON.restart}${t("restart")}</button><button class="bot-action danger" data-menu-action="delete" data-menu-name="${esc(b.name)}">${ICON.trash}${t("delete")}</button><button class="bot-action" data-menu-action="detail" data-menu-name="${esc(b.name)}">${CHART}Подробнее</button></div>`:""}</div>`}).join("");
    const filterOpen=UI.filter!=="all";return `<div class="screen home-screen"><div class="summary home-summary"><div class="summary-top"><div><div class="summary-count">${used}<span> / ${max}</span></div><div class="summary-meta">${t("slots")}</div></div><div class="summary-meta">${sub?.expires_at?`${t("expires")}: ${fmtDate(sub.expires_at)}`:""}</div></div><div class="summary-progress"><div style="width:${pct}%"></div></div><div class="summary-foot"><span>${used} ${LANG==="ru"?"использовано":"used"}</span><span>${Math.max(max-used,0)} ${LANG==="ru"?"доступно":"available"}</span></div><div class="summary-stats"><div class="summary-stat running" data-stat-filter="running"><div class="summary-stat-head"><span class="status-wave"></span><div class="summary-stat-value">${running}</div></div><div class="summary-stat-label">${LANG==="ru"?"Работают":"Running"}</div></div><div class="summary-stat installing" data-stat-filter="installing"><div class="summary-stat-head"><span class="status-wave"></span><div class="summary-stat-value">${installing}</div></div><div class="summary-stat-label">${LANG==="ru"?"Запускаются":"Starting"}</div></div><div class="summary-stat error" data-stat-filter="error"><div class="summary-stat-head"><span class="status-wave"></span><div class="summary-stat-value">${errors}</div></div><div class="summary-stat-label">${LANG==="ru"?"Ошибки":"Errors"}</div></div></div></div><div class="search-row"><label class="search-box">${SEARCH}<input id="bot-search" value="${esc(UI.query)}" placeholder="${LANG==="ru"?"Поиск юзербота":"Search userbot"}" autocomplete="off">${UI.query?`<button type="button" class="search-clear" id="search-clear">${X}</button>`:""}</label><button class="filter-button ${filterOpen?"active":""}" id="btn-filter" aria-label="Фильтр">${FILTER}</button></div><div class="filter-menu" id="filter-menu" style="display:${filterOpen?"flex":"none"}"><button class="filter-chip ${UI.filter==="all"?"active":""}" data-filter="all">Все</button><button class="filter-chip ${UI.filter==="running"?"active":""}" data-filter="running">Работают</button><button class="filter-chip ${UI.filter==="stopped"?"active":""}" data-filter="stopped">Остановлены</button><button class="filter-chip ${UI.filter==="error"?"active":""}" data-filter="error">Ошибки</button></div><div class="bot-list">${cards||`<div class="empty-search">${LANG==="ru"?"Ничего не найдено":"Nothing found"}</div>`}</div><button class="btn btn-primary" id="btn-open-bot">${ICON.plus}${t("installNew")}</button></div>`;
  };

  window.wireEvents = function(screen){
    document.getElementById("btn-back")?.addEventListener("click",goBack);document.getElementById("btn-settings")?.addEventListener("click",()=>navigateTo("settings"));document.getElementById("btn-open-bot")?.addEventListener("click",openInstallFlow);document.getElementById("btn-open-top")?.addEventListener("click",openInstallFlow);document.getElementById("btn-refresh-top")?.addEventListener("click",refreshHome);
    if(screen==="home"){
      const s=document.getElementById("bot-search");s?.addEventListener("input",e=>{UI.query=e.target.value;UI.menu=null;render();setTimeout(()=>{const n=document.getElementById("bot-search");n?.focus();n?.setSelectionRange(UI.query.length,UI.query.length)},0)});
      document.getElementById("search-clear")?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();UI.query="";render();setTimeout(()=>document.getElementById("bot-search")?.focus(),0)});
      document.getElementById("btn-filter")?.addEventListener("click",()=>{UI.filter=UI.filter==="all"?"running":"all";UI.menu=null;render()});
      document.querySelectorAll("[data-filter]").forEach(el=>el.addEventListener("click",()=>{UI.filter=el.dataset.filter;render()}));
      document.querySelectorAll(".summary-stat[data-stat-filter]").forEach(el=>el.addEventListener("click",()=>{UI.filter=el.dataset.statFilter;render()}));
      document.querySelectorAll(".bot-menu-button").forEach(el=>el.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();UI.menu=UI.menu===el.dataset.menuBot?null:el.dataset.menuBot;render()}));
      document.querySelectorAll(".bot-action[data-menu-action]").forEach(el=>el.addEventListener("click",async e=>{e.preventDefault();e.stopPropagation();const a=el.dataset.menuAction,n=el.dataset.menuName;UI.menu=null;if(a==="detail"){navigateTo("detail",{name:n});return}try{await handleBotAction(a,n)}catch(err){console.error(err)}}));
      document.querySelectorAll(".bot-card").forEach(el=>el.addEventListener("click",e=>{if(e.target.closest("button")||e.target.closest(".bot-actions"))return;navigateTo("detail",{name:el.dataset.bot})}));
    }
    if(screen==="detail")document.querySelectorAll(".action-btn[data-action]").forEach(el=>{el.addEventListener("click",()=>handleBotAction(el.dataset.action,NAV.params.name))});
    if(screen==="settings"){document.getElementById("row-language")?.addEventListener("click",()=>navigateTo("language"));document.getElementById("row-support")?.addEventListener("click",()=>openTelegramLink("https://t.me/userbothostchat"))}
    if(screen==="language")document.querySelectorAll("[data-lang]").forEach(el=>el.addEventListener("click",async()=>{const lang=el.dataset.lang;if(lang===LANG)return;LANG=lang;await setLanguage(lang);haptic("light");goBack()}));
  };

  const baseRender = render;
  window.render = function(){installStyle();const app=document.getElementById("app");const screen=STATE.authorized===false?"gate":currentScreen();const body={gate:screenGate,home:screenHome,detail:screenDetail,settings:screenSettings,language:screenLanguage}[screen]();app.innerHTML=renderHeader(screen)+body;syncTelegramBackButton();wireEvents(screen)};

  let busy=false;setInterval(async()=>{if(busy||STATE.loading||STATE.authorized===false)return;const screen=currentScreen();if(screen!=="home"&&screen!=="detail")return;if(document.querySelector(".bot-actions"))return;busy=true;try{const bots=await fetchBots();if(Array.isArray(bots)){STATE.bots=bots;render()}}catch(e){console.warn("DHost auto refresh",e)}finally{busy=false}},3000);

  installStyle();
  setTimeout(()=>{try{render()}catch(e){console.warn("DHost UI v2 init",e)}},0);
})();
